cc_library(
    name = "universe_resource",
    srcs = ["universe_resource.cc"],
    hdrs = ["universe_resource.hh"],
    deps = ["//light_control:light_universe_controller",
            "@server//json:json",
            "@server//resources:json_resource",
            "@server//:logging"]
)
