/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif


/* The following messages exceed 64kB in size: config_Runner */

/* The PB_FIELD_32BIT compilation option must be defined to support messages that exceed 64 kB in size. */
#ifndef PB_FIELD_32BIT
#error Enable PB_FIELD_32BIT to support messages exceeding 64kB in size: config_Runner
#endif
PB_BIND(config_ConstantNode, config_ConstantNode, AUTO)


PB_BIND(config_AdderNode, config_AdderNode, AUTO)


PB_BIND(config_SubtractorNode, config_SubtractorNode, AUTO)


PB_BIND(config_MultiplierNode, config_MultiplierNode, AUTO)


PB_BIND(config_DividerNode, config_DividerNode, AUTO)


PB_BIND(config_UniverseNode, config_UniverseNode, 4)


PB_BIND(config_UniverseNode_Light, config_UniverseNode_Light, 2)


PB_BIND(config_Node, config_Node, 4)


PB_BIND(config_Connection, config_Connection, AUTO)


PB_BIND(config_Runner, config_Runner, 4)



