cc_library(
    name="dmx",
    srcs=["dmx.cc"],
    hdrs=["dmx.hh"],
    visibility = ["//visibility:public"],
    deps=["//serial_control:serial_comms"]
)

cc_library(
    name="light_universe_controller",
    srcs=["light_universe_controller.cc"],
    hdrs=["light_universe_controller.hh"],
    visibility = ["//visibility:public"],
    deps=["//light_types:light_base"]
)

cc_library(
    name="light_effects",
    srcs=[],
    hdrs=["light_effects.hh"],
    visibility = ["//visibility:public"],
)
